name: Lerna version

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.npm_auto_push }}
        fetch-depth: 0

    - run: |
        git config --global user.name 'yeweili'
        git config --global user.email '782312713@qq.com'
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Lerna Version
      run: npx lerna version --yes
